// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzfpbtufctszlnkfqifr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6ZnBidHVmY3Rzemxua2ZxaWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTQ0NjQsImV4cCI6MjA2NjM5MDQ2NH0.aFdqAhr8kNnpvIop7euHCU_7TCCurxInky_kzhTuEg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);